#' Save everything to a specified location
#'
#' @param net
#' @param node_labels
#' @param network_list
#' @param nr_modules
#' @param nr_genes_per_module
#' @param disregulation_type
#' @param seed
#'
#' @return
#' @export
#'
#' @examples
save_generated_data<-function(net, counts, meta, gex_dir, disregulated_info=NULL){
  # save the data, plots and files in a directory
  gex.plot<-file.path(gex_dir, 'plots')
  dir.create(gex.plot, recursive = TRUE)

  # save plots before transforming data into data.table
  save_plots(counts, meta, gex.plot)

  # save counts and metadata
  gene_names<-rownames(counts)
  counts<-data.table::as.data.table(t(counts))
  colnames(counts)<-gene_names

  data.table::fwrite(counts, file = file.path(gex_dir, 'gex.tsv'), sep = '\t')
  data.table::fwrite(meta, file = file.path(gex_dir, 'metadata.tsv'), sep = '\t')
  # save network
  data.table::fwrite(net, file = file.path(gex_dir, 'net.tsv'), sep = '\t')
  if (!is.null(disregulated_info)){
    data.table::fwrite(disregulated_info, file = file.path(gex_dir, 'disregulation_info.tsv'), sep = '\t' )
  }
  return (gex_dir)
}




#' Subcluster a small graph and save the results to file
#'
#' @param sub Subgraph to be clustered and saved
#' @param network_dir Directory where nodes.tsv, edges.tsv, net.pdf will be saved (filenames autogenerated)
#' @param orig_graph The original graph which is needed to recover the edge directions
#'
#' @return NULL
#'
#' @export
#' @examples
#' collectri.file <- '/tmp/collectri.tsv'
#' net.dir <- '/tmp/subgraphs'
#' collectri <- loadOrDownloadCollectTRI(collectri.file)
#' colnames(collectri)<- c('source', 'target', 'sad')
#' graph_list<-clusterNetwork(collectri )

#' graph_list<-remove_irrelevant_networks(graph_list)
#' orig_graph<-createGraph(collectri)
#' for (g in graph_list){
#'  save_small_subgraph(g, net.dir, orig_graph)
#' }
save_small_subgraph<-function(sub, network_dir, orig_graph){

  # add number of nodes to filename
  counter <-igraph::vcount(sub)
  ## Add timestamp to avoid overwriting same sized graphs
  timestamp = as.numeric(format(Sys.time(), "%OS3")) * 1000

  local.dir<-file.path(network_dir, paste0('net_', counter, '_',timestamp))
  dir.create(local.dir, recursive = TRUE)
  # Create filename
  file.plot <- file.path(local.dir, paste0('net.pdf'))
  file.edge <- file.path(local.dir, paste0('edges.tsv'))
  file.node<-file.path(local.dir, paste0('nodes.tsv'))

  res<-restore_original_directionality(sub, orig_graph)

  # Layout and create submodules
  lay <- igraph::layout_with_kk(sub)

  # Plot network
  pdf(file = file.plot, width = 600, height = 600 )
  plot(res$clustering, res$subgraph , vertex.size = 5, edge.arrow.size = 1, vertex.label.cex = 1)
  dev.off()

  data.table::fwrite(res$egdelist, file = file.edge , sep = '\t')

  # save nodelist with community
  data.table::fwrite(res$nodelist, file = file.node, sep = '\t')
}
